[package]
name = "countdown-gif"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
gifski = "1.32.0"

[build-dependencies]
anyhow = "1.0.86"
rusttype = "0.9.3"
[build-dependencies.image]
version = "0.25.1"
default-features = false
features = ["png"]
