[package]
name = "countdown-gif"
version = "0.1.0"
edition = "2021"

[[example]]
name = "prepare-png"
path = "examples/prepare-png.rs"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
gifski = "1.32.0"

[dev-dependencies]
image = "0.25.1"
rusttype = "0.9.3"
